title: Project no-idea
author: A gh-pages noob
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Nice, some description to tweak Google.

theme: jekyll-theme-cayman