name: build and deploy current version to m2repo

# Controls when the workflow will run
on:
  # Workflow need to be triggered manually from github page
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job to deploy current version to github.io page
  deploy:
    # Github runner used to perform workflow
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    
      # Checks-out the repo contianing the source code
    - uses: actions/checkout@v3
      with:
        repository: mdo-over/mdo-over
        path: ./code
         
      # Checks-out the github.io page repo
    - uses: actions/checkout@v3
      with:
        repository: mdo-over/mdo-over.github.io
        ref: testOverwrite
        path: ./page
   
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: maven
       
      # Builds and deploys artifacts and javadoc locally on the github machine
    - name: Build mdo-over with Maven and deploy to page repo
      run: |
        mvn deploy -DaltDeploymentRepository=none::default::file:../page/m2repo
      working-directory: ./code
      
    - name: Add and commit changes in page repo
      uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
      with:
        # The arguments for the `git add` command (see the paragraph below for more info)
        # Default: '.'
        add: 'm2repo'
        push: 'origin testOverwrite'
        author-email: 'stefan.john@uni-marburg.de'
        message: 'update to deployed mdo-over in m2repo'
        cwd: './page'